export const WELL_KNOWN_OPC_UA_DATA_TYPES: Readonly<Record<number, string>> = {
  0: 'Null',
  1: 'Boolean',
  2: 'SByte',
  3: 'Byte',
  4: 'Int16',
  5: 'UInt16',
  6: 'Int32',
  7: 'UInt32',
  8: 'Int64',
  9: 'UInt64',
  10: 'Float',
  11: 'Double',
  12: 'String',
  13: 'DateTime',
  14: 'Guid',
  15: 'ByteString',
  16: 'XmlElement',
  17: 'NodeId',
  18: 'ExpandedNodeId',
  19: 'StatusCode',
  20: 'QualifiedName',
  21: 'LocalizedText',
  22: 'ExtensionObject',
  23: 'DataValue',
  24: 'Variant',
  25: 'DiagnosticInfo',
};

export const WELL_KNOWN_OPC_UA_NODE_CLASSES: Readonly<Record<number, string>> = {
  0: 'Unspecified',
  1: 'Object',
  2: 'Variable',
  4: 'Method',
  8: 'ObjectType',
  16: 'VariableType',
  32: 'ReferenceType',
  64: 'DataType',
  128: 'View',
};
